# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.99.99.99"
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  #config.vm.synced_folder "~/.ssh", "/home/vagrant/.ssh"
  config.vm.synced_folder "~/.dotfiles", "/home/vagrant/.dotfiles"
  config.vm.synced_folder ".", "/vagrant_setup/"
  config.vm.synced_folder "~/projects/vagrant/", "/home/vagrant/projects", type: "nfs"
  config.vm.provision :shell, :path => "setup/install_global.sh"
  config.vm.provision :shell, :path => "setup/install_user.sh", privileged: false
  # config.vm.provision :shell, :path => "setup/syncdotfiles.sh", privileged: false
end
